name: "static analysis"

on: ["pull_request", "push"]

jobs:
  static-analysis:
    name: "static analysis"
    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout"
        uses: "actions/checkout@v2"

      - name: "installing PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "7.4"
          ini-values: memory_limit=-1
          tools: composer:v2, cs2pr
          extensions: intl, bcmath, curl, openssl, mbstring, pdo, pdo_sqlite

      - name: "installing psalm"
        run: "composer require vimeo/psalm:^4.6 psalm/plugin-symfony:^2.2 --dev --no-update && composer require --no-update"

      - name: "installing dependencies"
        run: "composer update --no-interaction --no-progress"

      - name: "running static analysis"
        run: "vendor/bin/psalm --shepherd --stats"
